# Generated by Django 3.0.4 on 2020-04-01 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('dep_num', models.IntegerField(verbose_name='部门人数')),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('level', models.SmallIntegerField(choices=[(0, '最高权限'), (1, '管理权限'), (2, '基础权限')], default=2, verbose_name='用户权限')),
                ('photo', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户头像')),
                ('isDelete', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_title', models.CharField(max_length=30, verbose_name='工单标题')),
                ('telephone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('type', models.CharField(choices=[('repair', '维修'), ('clean', '清洁'), ('security', '安保')], max_length=30, verbose_name='报事类型')),
                ('address', models.CharField(max_length=30, verbose_name='服务位置')),
                ('receiver', models.CharField(blank=True, max_length=20, null=True, verbose_name='接受人')),
                ('status', models.SmallIntegerField(choices=[(0, '未完成'), (1, '审核中'), (2, '已完成')], default=0, verbose_name='工单状态')),
                ('order_time', models.DateTimeField(verbose_name='预约时间')),
                ('alter_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ord_text', models.TextField()),
                ('isDelete', models.BooleanField(default=False)),
                ('ord_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User', verbose_name='创建者')),
            ],
        ),
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_title', models.CharField(max_length=20, verbose_name='公告标题')),
                ('ann_text', models.TextField()),
                ('effective_time', models.DateTimeField(verbose_name='有效时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('alter_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isDelete', models.BooleanField(default=False)),
                ('ann_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User', verbose_name='创建者')),
            ],
        ),
    ]
